name: AI-Sound
on:
  workflow_dispatch:
jobs:
  Generate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "准备依赖模块"
        run: |
          mkdir record
          sudo apt-get install libsndfile1
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install --upgrade importlib-metadata
          pip install -r requirements.txt
          cd ys
          aria2c https://github.com/LemonFan-maker/Download-Models/releases/download/ys/ys.pth
          cd ..
      - name: "准备内核文件"
        run: |
          cd monotonic_align/
          python setup.py build_ext --inplace
      - name: "准备内网穿透服务"
        run: |
          aria2c https://github.com/ekzhang/bore/releases/download/v0.4.1/bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz
          tar -xvf bore-v0.4.1-x86_64-unknown-linux-musl.tar.gz
          chmod a+x bore
      - name: "启动服务"
        run: |
          sudo sysctl -w net.core.rmem_max=25000000
          nohup python main.py &
          ./bore local 8088 --to bore.pub
